import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { shadesOfPurple } from "@clerk/themes";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
export const metadata: Metadata = {
  title: "Plan Lab",
  description: "Generated by create next app",
  icons: "/plan.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadesOfPurple,
        variables: {
          colorPrimary: "#3b82f6",
          colorBackground: "#1a202c",
          colorInputBackground: "#2D3748",
          colorInputText: "#F3F4F6",
        },
        elements: {
          formButtonPrimary: "bg-gray-800 text-white hover:bg-gray-700",
          card: "bg-gray-900",
          headerTitle: "text-blue-400",
          headerSubtitle: "text-gray-400",
        },
      }}
    >
      {" "}
      <html lang="en" suppressHydrationWarning>
        <body className={`${inter.className} `}>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
            {/* <header></header> */}
            <div className="relative">
              <div className="absolute top-1/2 left-0 -translate-y-1/2 w-[300px] h-[300px] bg-purple-500/10 blur-3xl z-0 pointer-events-none rounded-full  " />
              <Header />
              <div className="absolute top-0 right-[5vw] w-[400px] h-[400px] bg-purple-600/10 blur-3xl rounded-full z-0 pointer-events-none" />
              <main className="min-h-screen pt-20"> {children}</main>
              <Toaster />
              <Footer />
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
